### ISSUE TITLE
/server command (plus fix)

### ISSUE THREAD

**Issue by Jazz23** [natiiix/KRelay#4]
Give the stats a default value of "" in the reconnect packet class so /server works. (and any other k relay functions that don't specify stats), so its not null when its sent to the servers.

**Comment by natiiix** [comment]
Oh, it took me quite a great amount of time to figure out you didn't mean the standard /server command, but rather the K-Relay /server command. I have no idea why anyone thought it was a good idea to override the /server command and completely change its behavior.
It was pretty easy to fix, but I'm going to remove the /server command from K-Relay now. I had no idea K-Relay changed the behavior of this command, I just thought it somehow broke it.
To change the active server, you should use /con or /connect. However changing the server this way will only result in a temporary change that will be negated as soon as you try to return to Nexus, so it is strongly advised to change the Default Server in K-Relay Settings instead. Even though this requires you to restart K-Relay.

**Comment by Jazz23** [comment]
/con will default to crazy client and take you off the proxy. I think /conn won't though (EDIT: it does still take you off the proxy, so since the client overrides the proxy its rip city), and yeah back before I knew about the /server K Relay command I did in fact change the default server every single time and reconnect and that was a nail in the tonail. M8be you could make /conn change the default server and switch servers at the same time? Don't know if that's too far away from the norm of K Relay, but honestly im going to do that to my personal copy, as well as making the command /serv rather than /server. Thanks for taking my advice and fixing the stats crap!

EDIT: I just added the auto default server changer and its flippin sexy definitely recommend it!

**Comment by natiiix** [comment]
CC has a setting for K-Relay users that changes /con to /conn.
You're supposed to change it manually. The /connect command does virtually nothing. It doesn't actually change the default server, so once you get back to Nexus, you're back on the default server, thus making it completely useless.
Not sure what "auto default server changer" you're talking about, because in the current state there is no easy way to switch servers on the go. It has been a top priority problem for quite a while, but no one has come up with a solution yet.

**Comment by natiiix** [comment]
If you could make a pull request with the changes, that would be actually very useful, because I can't really do much based on what you've said.
I've previously tried changing the DefaultServerName in Proxy, but that doesn't help since you'd need to create a new instance of either Client or State for it to have any effect, but that's just not happening.

**Comment by Jazz23** [comment]
k i spent like 30 minutes tryna get dat pull request garbo with no luck so just use this:

ReconnectHandler.cs:
https://pastebin.com/WZkxCUm4

FrmMainMetro.cs:
https://pastebin.com/BGqNSaNV

FrmMainMetro.Settings.cs:
https://pastebin.com/VbQdP0mb

(Note: It doesn't change the list box on the UI until after restart, besides that its functionally the same as switching the default server, clicking save settings, then restarting and spawning back in.)

Also top priority problem for a while? wtf i just wipped up an event and hooked it on the main form, are we talking about the same thing cause my fix took like 2 minutes, hopefully this is what you wanted me to pull request for idk reply if I'm wrong.

btw thanks for listening to me and responding so quick! Also this makes the /connect command the new /serv command useful. And yeah that /conn thing you were talking about is what I was alluding too I just couldn't find the setting in the crazy client and kinda forgot how it worked.

"you'd need to create a new instance of either Client or State for it to have any effect." nope, still takes effect ¯\_(ツ)_/¯. You can nexus without restarting in the new server and after restarting it shows up in settings. (tbh I'm surprised as well I was totally on ship with the have to restart philosophy but then I tested it and ploop.)

**Comment by natiiix** [comment]
I totally it before and it didn't work without creating a new instance of State in the Client. That's because the State constructor takes the DefaultServerName from Proxy, so unless you create a new instance, you never update it. Of course I didn't try to mess around with events because it seemed like an overkill at that point in time.
I'd just like to point out that I'm not a K-Relay developer and I had absolutely no part in making in. I merely maintain it. This means I have basically no knowledge of the code and therefore it's very difficult for me to change anything. So yeah, I've been looking into it, but I couldn't find anything so I postponed the idea until someone figures it out, which seems to be about now.
If you don't have a public fork of this repository, you're not able to create a PR, so that's probably why it didn't work. I'll look into it.

**Comment by natiiix** [comment]
Please look at [this branch](https://github.com/natiiix/KRelay/tree/server_change_test) and tell me if everything is okay.

**Comment by Jazz23** [comment]
dude ik you didn't make it and ik you just update it and add a little pissaz here and there, and I'm not a K Relay developer I'm just a guy with some source code who was stupid enough to try and change the default without restart. Yeah that repository looks fine. And I did try and make my own public fork but It wasn't showing up as an option don't know if there is like a delay or how it even knows that mines a K Relay fork but idk it looks fine this is gonna be sweet it becomes mainstream, goodbye unnecessary restarting!

(also I'm looking into the code to see why this works, I can see an easy solution if it didn't but it does so I'm doing a little head scratching)

**Comment by natiiix** [comment]
Thanks a lot for your contribution.
I never looked at the "/connect" command much before.
I was really surprised by how easily you were able to make the change permanent, because the code you added was the very same code the "Save Settings" button did. However the changes made by saving the settings didn't take effect unless you restarted K-Relay, which isn't the case for your code somehow.
When you change the settings, but don't do the reconnect, nothing is going to happen. It appears that you must send the reconnect packet to the client in order for it to be actually able to switch the server. 
Back before when I tried it, saving the settings, going back to menu in the client and then clicking "Play" again used to still put you on the old server. For some reason, even when you connected to the game again, the State property in your Client instance didn't change and you stayed connected to the original server.
Since this didn't work, I didn't even consider that the "/connect" command was possible to be fixed. So when I saw how little were the changes you had to make to the code, I was very surprised that it actually worked because I definitely didn't expect it to be enough.
I've asked a few people who contribute to K-Relay to test these new changes and as soon and I'm sure it works correctly, I'll merge the test branch with the master branch. There is a Discord server for developers of RotMG hacks on MPGH. If you'd like to join, please PM me on MPGH and I'll send you an invitation.
PS: And yeah, GitHub has quite some delay when it comes to making changes to repositories. I've noticed that too.

**Comment by Jazz23** [comment]
literally exactly what I'm thinking. (also the "State property" you speak of is literally a public string, you could just set that so you don't have to make a new client or anything, but hey it magically works so boom bam bop) also my discord is Jazz#0001 if you wanted to actually have a real convo this comment thing is trash.
